### ISSUE TITLE
Popover not visible on screen if called inside of SliverAppBar action

### ISSUE THREAD

**Issue by JonasHiltl** [minikin/popover#37] opened 2021-05-29 00:12 UTC
**Describe the bug**
I'm calling the `showPopover` function from an action of the `SliverAppBar` but the Popover is not shown on the screen. I guess that it is positioned outside of the screen.

**Code:**
```dart
class ManageDocuments extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    final sessionState = context.watch<Verified>();
    return CustomScrollView(
      physics: const BouncingScrollPhysics(),
      slivers: <Widget>[
        SliverAppBar(
          // if floating is true the appbar becomes instantly visible if scrolled towards top
          // if it's false the appbar is only visible if completly scrolled back to top
          floating: true,
          expandedHeight: 60.0,
          backgroundColor: Theme.of(context).scaffoldBackgroundColor,
          title: Text(
            "Manage Documents",
            style: TextStyle(color: Theme.of(context).colorScheme.onBackground),
          ),
          centerTitle: true,
          actions: [
            IconButton(
              icon: Icon(
                Icons.add,
                color: Theme.of(context).colorScheme.onBackground,
              ),
              onPressed: () => showPopover(
                context: context,
                bodyBuilder: (context) => Column(
                  children: [
                    Text(L.of(context).patientQuestionnaire),
                    Text(L.of(context).patientQuestionnaire),
                    Text(L.of(context).patientQuestionnaire),
                  ],
                ),
                direction: PopoverDirection.bottom,
              ),
            ),
          ],
        ),
      ],
    );
  }
}

```

**Expected behavior**
I expected the Popover to be positioned below the `IconButton` in the appBar, with the direction of `PopoverDirection.bottom`

**Screenshots**
I already clicked on the action `IconButton` and the background get's dimmed but the popover is out of screen.
![Unbenannt](https://user-images.githubusercontent.com/71456708/120051757-370dbb80-c022-11eb-8f3d-ba9c9e98f97c.JPG)

**Smartphone (please complete the following information):**
 - Device: Pixel C API 30
 - OS:  Android 11.0

**Comment by minikin** [comment] 2021-05-29 07:58
@JonasHiltl Thank you for your report. I'll take a look in the next couple of days.

**Comment by minikin** [comment] 2021-06-01 08:57
@JonasHiltl I cannot reproduce it. So I created a [project to play with a popover](https://github.com/minikin/popover_playground). Would you mind to create a reproducible example there?

**Comment by JonasHiltl** [comment] 2021-06-01 12:49
I just ran your test project and could reproduce the issue. I'm running it on a Pixel C emulator and the popover doesn't show but the screen darkens, as seen in the image above. I guess that the issue either is caused by the Pixel C device or the `CustomScrollView` which might position the popover outside of the screen.

**Comment by Liliana99** [comment] 2021-06-02 11:54
Same issue, In my case I have a floating Navigation Bar, the body of the screen is a SingleChildScrollView, the behaviour at the moment to call popover is not visible, at the background is appears somethings like these screen as @JonasHiltl  describe.

**Comment by minikin** [comment] 2021-06-02 13:50
@Liliana99 @JonasHiltl 
Thanks, I was able to reproduce it. I'll try to fix it asap. 
If you have  ideas on how to fix it, you're very welcome 😉

**Comment by pythonhubpy** [comment] 2021-06-25 19:54
Facing the same issue. I think this needs to be fixed asap.

**Comment by pythonhubpy** [comment] 2021-06-26 13:51
What may be causing this issue any idea? So that I could help as well

**Comment by minikin** [comment] 2021-06-28 12:47
@pythonhubpy @JonasHiltl @Liliana99 
I did some investigation on a weekend. I discovered that widgets are actually present in the widgets tree. 
But I didn't have enough time to investigate why they are not displayed on a screen. Any thoughts?

**Comment by pythonhubpy** [comment] 2021-06-28 13:34
Trying to figure it out. Should we use some `Sliver` widgets? Would it may be a cause?

**Comment by minikin** [comment] 2021-06-28 14:31
@pythonhubpy I'm not sure.  We (or I) implemented something in the wrong way, because [this thing works](https://github.com/minikin/popover_playground/blob/main/lib/main.dart#L40).

**Comment by pythonhubpy** [comment] 2021-06-28 19:57
I have a question can't we render this with an `Overlay` widget provided by flutter. We actually just need to calculate the position for the `OverLayEntry` I don't know whether it's a good idea just asking for suggestion @minikin.

**Comment by minikin** [comment] 2021-06-28 20:52
@pythonhubpy Thanks for trying things, really appreciate it!

Yes, we can use `Overlay` but it has other implications in complex systems (think about something like Netflix)

I think that we need to start [here](https://github.com/minikin/popover/blob/main/lib/src/popover_item.dart) and dig deep if needed. 
 
We have this one #21 for a long time. Maybe that's the moment to finally do it 🤓 The idea to make it work like in e.g. `CupertinoActionSheet` works.

Plus, we need to keep in mind the backward capability of public API.

**Comment by pythonhubpy** [comment] 2021-06-28 21:18
Will work on it.

**Comment by pythonhubpy** [comment] 2021-07-10 07:47
Tried making different changes in PopoverItem.dart but couldn't resolve the issue. Any ideas @minikin

**Comment by minikin** [comment] 2021-07-13 08:10
@pythonhubpy I'll back from vacation next week and will have a look in greater detail into this issue.

**Comment by pythonhubpy** [comment] 2021-07-13 08:13
Sure

**Comment by IgorDevJS** [comment] 2021-07-25 18:06
hi guys, i'm br so sorry my english haha

I was getting the same error inside SliverPersistentHeader when calling the showPopover function from inside this widget
but I managed to solve it by creating a new widget just for the button that will call the popover, thus passing the context of the button Widget, and now it works

Here's an example of the workaround I made:
https://github.com/IgorDevJS/popover_playground/commit/2baeb14e11b5e62b060afdfff3ea711f6537ca64

**Comment by minikin** [comment] 2021-07-26 07:53
@IgorDevJS  thank you very much for sharing 🙏

It looks like it's only partially fix the issue for me:
<img width="1312" alt="Screenshot 2021-07-26 at 9 49 15 AM" src="https://user-images.githubusercontent.com/4456735/126952875-c3c82828-6079-4550-b960-946dc5989aca.png">

+ animation transition is super laggy.

**Comment by IgorDevJS** [comment] 2021-07-26 12:34
You are welcome!

Yes true.

I quickly googled and found this, I don't know if it can improve
https://github.com/flutter/flutter/issues/31059#issuecomment-500961641

When I have some time here I can try to apply and run some tests.

**Comment by minikin** [comment] 2021-07-26 12:43
@IgorDevJS I don't think it can help us here. Moreover, as you can see on a screenshot, a layout of a popover is broken.

**Comment by IgorDevJS** [comment] 2021-07-26 13:54
@minikin 
Hmm OK

But the broken layout problem I don't think is related to the popover problem in SliverAppBar

It seems to be because the button is too far in the corner and because it is too small the arrow ends up outside the popover

In my project I'm developing, the button has a larger width and the popover layout is ok

**Comment by pythonhubpy** [comment] 2021-08-09 19:35
Any updates on this @minikin?

**Comment by minikin** [comment] 2021-08-10 14:57
@pythonhubpy Unfortunately, I don't have time now to work on this issue.  However, if someone finds a solution, I'd be happy to review PR and test a solution.

**Comment by pythonhubpy** [comment] 2021-08-10 15:15
Tried out different ways I couldn't find out what is the exact issue.

**Comment by FCAppsPeople** [comment] 2021-09-23 00:31
You need to pass the correct context when displaying the popOver menu. In your code you are passing the context of the ManagerDocument Widget, so the menu is showing off screen. You have two options in this case, either putting it inside another builder or creating a specific widget for it to pass its context.

**Comment by felipecs81** [comment] 2021-09-23 00:32
You need to pass the correct context when displaying the popOver menu. In your code you are passing the context of the ManagerDocument Widget, so the menu is showing off screen. You have two options in this case, either putting it inside another builder or creating a specific widget for it to pass its context.

**Comment by zhouxiaofu** [comment] 2021-12-27 10:00
Use StatefulBuilder  to wrap widget

**Comment by minikin** [comment] 2022-01-30 09:58
Sounds like we can close it. Feel free to reopen it if you think we can improve something. Thanks to everyone!

**Closed by minikin** 2022-01-30 09:58 UTC
Labels: bug, enhancement

**Comment by droidchief** [comment] 2024-05-31 13:37
The issue with the popover positioning is due to the context being used. Instead of using the context of the whole page, you need to get the context of the button itself to position the popover correctly. Here is an approach I used to ensure the popover is positioned relative to my button.

**Steps:**

**1 Wrap the button with a Builder widget to get its context.**

**2 Use the context of the Builder widget to show the popover.**

`Builder(
                    builder: (context) {
                      return ElevatedButton(
                          onPressed: () {
                            showPopover(
                              context: context,
                              bodyBuilder: (context) =>
                              const Center(
                                  child: Text(
                                "Hello Flutter!",
                              )),
                              width: 200,
                              height: 100,
                              backgroundColor: Colors.white,
                              radius: 12,
                              direction: PopoverDirection.top,
                            );
                          },
                          child: const Text("Show popup"));
                    },
                  )`


[Check out my solution](https://stackoverflow.com/questions/78459386/how-to-show-a-widget-in-a-popover-in-flutter-i-got-blank-screen/78559777#78559777)
